### PR TITLE
Fix issues

### LINKED ISSUE #25: preventable to get an "empty" character with an id
I see how you killed the bug, but it seems somewhat hacky. Isn't it preventable to get an "empty" character with an id in the first place somehow?

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/23#discussion_r1064192027_

### LINKED ISSUE #26: This comment seems to be outdated
This comment seems to be outdated

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/23#discussion_r1064192072_

### LINKED ISSUE #27: make a custom hook by extracting the logic
> I'd love to receive a feedback in AllSpecies.tsx. Especially I want to know where is the good place to put reducer functions.

I wouldn't mind having this reducer logic in this file as it's small enough and encapsulated in this domain. Though it's ok to leave them here, if you don't feel comfortable leaving them in this file then I'd advise you to make a custom hook by extracting the logic so that you can separate the logic part of this file and render part of it. It could be called something like; `useSortCharacters`

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/23#discussion_r1064188127_

### LINKED ISSUE #28: narrow this type to a union of string literals
I think you can narrow this type to a union of string literals. In this use case, you know the selected value is always either `height` or `mass`, so I'd recommend you create an enumerator-like object so that you can couple all the logic looking at the single source of truth. This is phenomenally effective when all the logic is based on a single factor/domain. In this case, we know they all are trying to "sort" characters with these keys, so it's ok to couple them together to look at the single place. 

This is just a pseudo code so don't count on it lol but I hope you get the idea.
```typescript

// enum like object - make sure to leave a comment about why you use this object as it has multiple dependencies. 
// Means that a single change on this object can cause a big mess 
const SORT_FACTOR = {
  MASS: "mass",
  HEIGHT: "height",
  DEFAULT: "default" // you might not need this value
} as cosnt

// "mass" | "height" | "default"
type SortFactor = typeof SORT_FACTOR[keyof typeof SORT_FACTOR]

type CharacterState = {
  originalCharacters: ModifiedCharacter[]
  modifiedCharacters: ModifiedCharacter[]
  selectedValue: SortFactor // here, you narrowed the type from "string" to "mass" | "height" | "default"
}

// this function now can accept "mass" | "height" | "default". You might want to handle the case "default" explicitly
const sort = (characters: ModifiedCharacter[], key: SortFactor) =>
  characters.sort((a, b) => (b[key] || 0) - (a[key] || 0))

[...]

{
    Object.keys(SORT_FACTOR).map(sortFactorKey => (
        // You might need some logic or CSS trick to change the value to the title case
        <option value={SORT_FACTOR[sortFactorKey]}>{SORT_FACTOR[sortFactorKey]}</option>
     ))
}
```

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/23#discussion_r1064191307_

### LINKED ISSUE #30: abstract this function at a higher level
It's better for you to abstract this function at a higher level as you have assigned `BrowserRouter` in multiple places too. Prob you can even combine this with Redux's `<Provider />` as well so that you won't need to invoke different functions on each test cases

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/29#discussion_r1084819650_

### LINKED ISSUE #31: It could be something like; `sortKey` or `sortFactor`
[nitpick] - I'm not really impressed by this type's name as `Key` is way too vague. It could be something like; `sortKey` or `sortFactor` or something else.

_Originally posted by @kei95 in https://github.com/Lada496/star-wars-list/pull/23#discussion_r1064188871_

### PR DESCRIPTION
**Pull request by Lada496**
#### What Feature I added
- [modifed CharacterItem.test.tsx to reduce duplicate code](https://github.com/Lada496/star-wars-list/commit/a22d903d802935394c12e967af96e7459a3113b3): related to #15 
- fixed #25, fixed #26: Modified CharacterItem no to render CharacterDetails when no detailed data available (https://github.com/Lada496/star-wars-list/commit/dec43aa7aeb753d5a503db4d129f70daa022cca7)
- fixed #27, fixed #28, fixed #31: created useModifiedCharacters and made use of [this abstraction](https://github.com/Lada496/star-wars-list/pull/23#discussion_r1064191307) (https://github.com/Lada496/star-wars-list/commit/867681657ebcd0c6f85f214a24d969ec01c89003)
- fixed #30 : created renderWithWrappers (https://github.com/Lada496/star-wars-list/commit/69475025920b47254c34f90b528e9916571d2d87)

#### Wired Findings
I found this test fails when I assign ` const height = await screen.queryByText(/height/i)` before user click event because it returns `null` when it tests `expect(height).toBeInTheDocument()`. I couldn't find any logical explanation why it fails and `expect(height).not.toBeInTheDocument()` passes. If you have any suggestion about it please let me know.
```javascript
// Pass
test('show details when users click the button and hide them when users click it again', async () => {
    render(
      <UnorderedList>
        <CharacterItem character={withBmiCharacter} />
      </UnorderedList>,
    )
    // Assign 
    const viewDetailsButton = screen.getByRole('button', { name: /view details/i })

    // Act - interact by pressing button
    userEvent.click(viewDetailsButton)

    // Assign
    const height = await screen.queryByText(/height/i)

    // Assert - make sure the height element is in the screen
    expect(height).toBeInTheDocument()

    // Assign - hide details
    const hideDetailsButton = await screen.getByRole('button', { name: /hide details/i })

    // Act
    userEvent.click(hideDetailsButton)

    // Assert - no hight button
    expect(height).not.toBeInTheDocument()
  })
```

```javascript
// Fail
test('show details when users click the button and hide them when users click it again', async () => {
    render(
      <UnorderedList>
        <CharacterItem character={withBmiCharacter} />
      </UnorderedList>,
    )
    // Assign - grab all expected elements to be used in the test
    const viewDetailsButton = screen.getByRole('button', { name: /view details/i })
    const height = await screen.queryByText(/height/i)

    // Act - interact by pressing button
    userEvent.click(viewDetailsButton)

    // Assert - make sure the height element is in the screen
    expect(height).toBeInTheDocument()

    // Assign - hide details
    const hideDetailsButton = await screen.getByRole('button', { name: /hide details/i })

    // Act
    userEvent.click(hideDetailsButton)

    // Assert - no hight button
    expect(height).not.toBeInTheDocument()
  })
```

#### To do
- look into https://github.com/Lada496/star-wars-list/pull/23#discussion_r1068718333 when implement the filter feature

#### Others
Please disregard the last commit. I stupidly modified main branch and tried to fix it🤦‍♀️

### CODE REVIEW

**Comment by koh1project** [comment]
@Lada496  Great work, Yuko! I am always amazed by how you have done weekly. I want to confirm your findings. 

Before a user clicks the "view details button," there is no text "height" on the screen, so `await screen.queryByText(/height/i)` should return null before the click event.


image


I tried 2 patterns:
```
expect(null).not.toBeInTheDocument() // -> true
expect(null).toBeInTheDocument()  // -> fails. Error message: received value must be an HTMLElement or an SVGElement. Received has value: null
```

So, these result and your findings seem reasonable to me, at this moment. Can I have more detail thought on you that where you got stuck?

**Comment by Lada496** [comment]
> So, these result and your findings seem reasonable to me, at this moment. Can I have more detail thought on you that where you got stuck?


@koh1project 
Thank you for your replay! This is actually from comparison of the results between `expect(height).not.toBeInTheDocument()` and `expect(height).toBeInTheDocument()` in that test.
In failed test code, I assigned `const height = await screen.queryByText(/height/i)` before `userEvent.click(viewDetailsButton)` assuming this user's action changes `height` value to be non-null. However the test result shows `height` remains to be `null` even after clicking `viewDetailsButton`.
On the other hand, in passed test code, I assigned `const height = await screen.queryByText(/height/i)` after `userEvent.click(viewDetailsButton)`, which means `height` is originally non null. Interestingly `expect(height).not.toBeInTheDocument()` passes implying `userEvent.click(hideDetailsButton)` changes `height` value to be `null` this time.
The point is both cases assign before user's operation but one doesn't change assigned value but the other does.
So my question is what makes this difference. One hypothesis based of this observation would be that `null` can't be changed but non-null can but I can't find any resources so far☹️. Hope it does make sense...
Untitled-2023-01-18-1846

**Comment by kei95** [comment]
@koh1project lol you have beaten me to it. @Lada496 don't mind me if I'm rephrasing what he said already.

> Wired Findings
I found this test fails when I assign  const height = await screen.queryByText(/height/i) before user click event because it returns null when it tests expect(height).toBeInTheDocument(). I couldn't find any logical explanation why it fails and expect(height).not.toBeInTheDocument() passes. If you have any suggestion about it please let me know.

So the reason `await screen.queryByText(/height/i)` doesn't work is that the API `screen.queryByText` simply looks into the rendered virtual DOM in your test suite. Since you have logic to hide certain UI elements in [CharacterItem.tsx](https://github.com/Lada496/star-wars-list/blob/953abb968237e240d5bc6c729f7609ff1bd86ed3/src/components/CharacterItem/CharacterItem.tsx), the hidden elements don't **EXIST** in your virtual testing suite. The reason you are getting a such an error is that simply you are trying to access the element that doesn't exist, and that's why you can access it after pressing the view detail button as it changes the state of your component that results in changing what's rendered on virtual DOM. Below is an (over)simplified tree graph 
of the DOM being tested. I hope that makes sense.

Screenshot 2023-01-28 at 4 58 51 PM

**Comment by Lada496** [comment]
@kei95 @koh1project Thank you both! I finally got it🙌

**Comment by kei95** [comment]
@Lada496 Lol wait I think I finally got your question now that I saw your diagram. Basically `screen.queryByText` doesn't retry or update once it's invoked. If you wanna reuse it, you need to abstract the query rather than the function. The following is the tweaked version of your test that makes a variable out of the query to be reused. Also, you can find each query's behavior in [the document](https://testing-library.com/docs/queries/about). Btw, you had several un-meaningful `await`s in your test suite

```typescript
  test('show details when users click the button and hide them when users click it again', async () => {
    render(
      <UnorderedList>
        <CharacterItem character={withBmiCharacter} />
      </UnorderedList>,
    )

    const viewDetailsButton = screen.getByRole('button', { name: /view details/i })
    const heightQuery = /height/i // to be reused

    // make sure undesired element is rendered by default
    expect(screen.queryByText(heightQuery)).not.toBeInTheDocument()

    // show details
    userEvent.click(viewDetailsButton)

    expect(screen.queryByText(heightQuery)).toBeInTheDocument()

    const hideDetailsButton = screen.getByRole('button', { name: /hide details/i })

    // hide details
    userEvent.click(hideDetailsButton)

    expect(screen.queryByText(heightQuery)).not.toBeInTheDocument()
  })
```

**Comment by koh1project** [comment]
Thank you @kei95 and @Lada496, this opportunity also helps me recognize the importance of knowing the exact point where the question comes from🙌

File: src/hooks/useModifyCharacters.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
+import { useReducer } from 'react'
```
Comment (kei95) [inline src/hooks/useModifyCharacters.ts:1]: Good job Yuko! TypeScript usage in this file is beautiful🪄

File: src/hooks/useModifyCharacters.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+// "mass" | "height"
+export type SortFactor = typeof SORT_FACTOR[keyof typeof SORT_FACTOR]
+
+type CharacterState = {
+  originalCharacters: ModifiedCharacter[]
+  modifiedCharacters: ModifiedCharacter[]
+  selectedValue: SortFactor | ''
+}
+
+type CharacterAction = { type: 'sort'; sortFacter: CharacterState['selectedValue'] }
```
Comment (kei95) [inline src/hooks/useModifyCharacters.ts:19]: Prob from my typo but I think it's `factor` instead of `facter`

File: src/hooks/useModifyCharacters.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    case 'sort':
+      if (action.sortFacter === 'height' || action.sortFacter === 'mass') {
+        const newModifiedCharacters = [...state.modifiedCharacters]
+        sort(newModifiedCharacters, action.sortFacter)
+        return {
+          originalCharacters: state.originalCharacters,
+          modifiedCharacters: newModifiedCharacters,
+          selectedValue: action.sortFacter,
+        }
+      }
```
Comment (kei95) [inline src/hooks/useModifyCharacters.ts:35]: This part of type narrowing is 💯

File: src/testHelpers/renderWithWrappers.tsx [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import { BrowserRouter } from 'react-router-dom'
+import { Provider } from 'react-redux'
+import { Store } from '@reduxjs/toolkit'
+import { render } from '@testing-library/react'
+import userEvent from '@testing-library/user-event'
+
+export const renderWithWrappers = (ui: React.ReactElement, store: Store, { route = '/' } = {}) => {
```
Comment (kei95) [inline src/testHelpers/renderWithWrappers.tsx:7]: Love this abstraction

File: src/App.test.tsx [hunk 5]
```diff
@@ -66,49 +56,32 @@ describe('App', () => {
...
-  test('Redirect to All characters page when user visit any bad path', () => {
-    renderWithRouter(
-      <Provider store={store}>
-        <App />
-      </Provider>,
-      { route: '/pathname-that-does-not-match-any-species-name' },
-    )
+  test('Redirect to All characters page when user visit any bad path', async () => {
+    const { getByRole } = renderWithWrappers(<App />, store, {
+      route: '/pathname-that-does-not-match-any-species-name',
```
Comment (kei95) [inline src/App.test.tsx:80]: I love how descriptive this mocked route name is

File: src/components/CharacterItem/CharacterItem.test.tsx [hunk 6]
```diff
@@ -46,23 +43,45 @@ describe('CharacterItem', () => {
...
+    // Assign - hide details
     const hideDetailsButton = await screen.getByRole('button', { name: /hide details/i })
 
-    // hide details
+    // Act
     userEvent.click(hideDetailsButton)
-    const noHeight = await screen.queryByText(/height/i)
-    expect(noHeight).not.toBeInTheDocument()
+
+    // Assert - no hight button
```
Comment (kei95) [inline src/components/CharacterItem/CharacterItem.test.tsx:84]: [nitpick] - This is my personal preference so you won't need to follow it, but I'd rather not write comments such as `assign act assert` as it can be quite noisy. You can see where's assigned, act, and assert as testing lib names each API quite declaratively so I won't mind seeing tests without comments that suggest which role each line is, but the good intention to explain the test with comments like `make sure height element is in the screen`!

**Comment by Lada496** [comment]
@kei95 I just fixed what you pointed out in this PR. Please take a look🙏
p.s) I tried using cs50 way of comment style for this time (https://cs50.readthedocs.io/style/c/#comments), not sure it's common in JavaScript world though.

**Comment by kei95** [comment]
>  I just fixed what you pointed out in this PR. Please take a look🙏
p.s) I tried using cs50 way of comment style for this time (https://cs50.readthedocs.io/style/c/#comments), not sure it's common in JavaScript world though.

Looks good! I just casually saw the page, and I could agree with the contents of it. One tip that I can give you for JS/TS specific comments is that you wanna use [JSCods](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) instead of the regular one for function/variable since it provides support from IDE.

Playground: https://www.typescriptlang.org/play?#code/PTAECUFMBcCcFcB2BnUBDUs2ICYHsBbUReAgI0llADNZDQBGUaPRgBgFgAoapAY2gBLPIlABzGOGz4CAOVIVYACgCUoAN7dQmGPFiiAsmmgALAHTUANnjzKjps1lyFVoAFTs1AakYBubgC+3NzAbh5Q0Hoo6JjS9CTklDR0REws7O7A3LyIAsKiEtBSznIKlADqgqYAUgDKACJ4fK6aXNqwuvqg9uZWNnbG5k4yrh4MbN5+gcFcIKAA7iaQogCeePCgJngAbkk7lAA0oGsb8+uWOKDIkJCgVajQKwAOtziQ1IKIVfmg3IXFMnkiWUKn8szAi2Wx3Wm32VDhRxOC3Ol2ut3uzGer3en2+IlAPj4hAIy2gf0kcVKwMqNQaTVUYJCYVAABUTIJUByYkSCCTENAaLZWZBkNAWVi7tBrpZqJluI8XsLReLFQBeDRaUChDwATRhfGwoHwzCWVzQJNA+NMt0QIugkEu2zQlng6NECtubiybUFeAAXKAAETUGyB6ZcEJgLa7WCfMSWmPI+AXcSCXbQjbW0A8vkCq2mp0uyDZfhCfEhvBKPBkABWAZZdpVkAA2sHQwBdNTqAJAA

### Regular comment
Screenshot 2023-01-29 at 1 01 53 PM

### JSDocs
Screenshot 2023-01-29 at 1 01 58 PM

### JSDocs on type itself
Screenshot 2023-01-29 at 1 04 34 PM

### JSDocs on nested value
Screenshot 2023-01-29 at 1 04 39 PM

**Review by kei95 — APPROVED** [review]

**Review by koh1project — APPROVED** [review]
